### ISSUE TITLE
Did you make a RNN and LSTM as mentioned in the README?

### ISSUE THREAD

**Issue by kazzastic** [arnavbansal1/WebMD-Scraper#2]
Did you? @arnavbansal1

**Comment by arnavbansal1** [comment]
Hi there, @kazzastic. I believe I worked on some models but did not fully complete that side of the project and hence this is the upload for the WebMD-Scraper portion. Hope that answers your question, thanks.

**Comment by kazzastic** [comment]
It sure does answer the questions, thanks for this project too!
